title: 'hyeonbell'
description: "."
baseurl: "/"
url : "https://hyeonbell.github.io/"

header_pages:
  - index.md

style: hacker

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown
theme: b2a3e8/jekyll-theme-console
